# Generated by Django 4.1.3 on 2022-11-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Post name')),
                ('text', models.TextField(verbose_name='Post text')),
                ('img', models.ImageField(upload_to='media', verbose_name='Post image')),
                ('date', models.DateTimeField(verbose_name='Post date')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
