# Generated by Django 4.1.3 on 2022-11-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Post name'),
        ),
        migrations.AddField(
            model_name='post',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Post name'),
        ),
        migrations.AddField(
            model_name='post',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Post name'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Post text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_hy',
            field=models.TextField(null=True, verbose_name='Post text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Post text'),
        ),
    ]
